StreamLinerApp/Areas/scp/Controllers/FieldController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StreamLinerEntitiesLayer.Entities;
using StreamLinerLogicLayer.Services.FieldServices;
using StreamLinerLogicLayer.Services.FieldTypeServices;
using StreamLinerRepositoryLayer.IRepositories;
using StreamLinerViewModelLayer.ModelDTO;

namespace StreamLinerApp.Areas.scp.Controllers
{
    [Area("scp")]
    public class FieldController : Controller
    {
        private readonly IField _field;
        private readonly IFiedlType _fielType;
        private readonly IMapper _mapper;
        string app = "Admin";
        string ctrl = "Fields";
        public FieldController(IField field, IMapper mapper, IFiedlType fielType)
        {
            _field = field;
            _mapper = mapper;
            _fielType = fielType;

        }
        public async Task<IActionResult> Index()
        {
            ViewData["application"] = app;
            ViewData["action"] = " ";
            ViewData["controller"] = ctrl;
            var fields = await _field.GetAllField();
            return View(fields);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewData["application"] = app;
            ViewData["action"] = " New Field";
            ViewData["controller"] = ctrl;
            var filefiels = await _fielType.GetAlltypes();
            ViewData["TypeId"] = new SelectList(filefiels, "TypeId", "Type");

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(FieldDTO field)
        {

            if (ModelState.IsValid)
            {
                await _field.AddField(field);
                return RedirectToAction("Index");
            }

            var fileFields = await _fielType.GetAlltypes();
            ViewData["TypeId"] = new SelectList(fileFields, "TypeId", "Type", field.TypeId);

            return View(field);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null) return NotFound();
            ViewData["application"] = app;
            ViewData["action"] = " Edit Field";
            ViewData["controller"] = ctrl;
            var field = await _field.GetFieldById(id);
            var fileFields = await _fielType.GetAlltypes();

            ViewData["TypeId"] = new SelectList(fileFields, "TypeId", "Type", field.TypeId);

            return View(field);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(FieldDTO field)
        {

            if (ModelState.IsValid)
            {



                var result = _field.UpdateField(field);

                return RedirectToAction("Index");

            }
            ModelState.AddModelError("", "Error updating field");
            var fileFields = _fielType.GetAlltypes().Result;

            ViewData["TypeId"] = new SelectList(fileFields, "TypeId", "Type", field.TypeId);
            return View(field);


        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null) return NotFound();
            ViewData["application"] = app;
            ViewData["action"] = " Delete Field";
            ViewData["controller"] = ctrl;
            var field = await _field.GetFieldById(id);
            var fileFields = await _fielType.GetAlltypes();

            ViewData["TypeId"] = new SelectList(fileFields, "TypeId", "Type", field.TypeId);

            return View(field);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
           _field.DeleteField(id);

            return RedirectToAction("Index");
        }



    }
}

StreamLinerApp/Areas/scp/Views/Field/Create.cshtml
 @model StreamLinerViewModelLayer.ModelDTO.FieldDTO 

 

<br />
<div class="container">
    <h3> @ViewData["controller"] -   @ViewData["action"]   </h3>
</div>
<hr />

<div class="container mt-5">

    <div class="row">

        <div class="col-md-6">


            <form method="post"  asp-action="Create" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="mb-3">
                    <label asp-for="FieldName" class="form-label"></label>
                    <input asp-for="FieldName" type="text" class="form-control" >
                </div>
                <div class="mb-3">
                    <label asp-for="TypeId" class="form-label"></label>
                    <select asp-for="TypeId" class="form-select" asp-items="ViewBag.TypeId">
                        <option value="0">--Select Type--</option>
                    
                    </select>
                </div>
                <div class="mb-3">
                    <label asp-for="Placeholder" class="form-label"></label>
                    <input asp-for="Placeholder" type="text" class="form-control">
                </div>
              

                <button type="submit" class="btn btn-primary">Save</button>
                <a asp-action="Index" class="btn btn-secondary">Back</a>
            </form>
        </div>
    </div>
</div>

StreamLinerApp/Areas/scp/Views/Field/Delete.cshtml
 @model StreamLinerViewModelLayer.ModelDTO.FieldDTO


@{
    ViewData["Title"] = "Fields";
}
<br />
<div class="container">
    <h3> @ViewData["controller"] -   @ViewData["action"]   </h3>
</div>
<hr />

<div class="container mt-5">

    <div class="row">

        <div class="col-md-6">

            <input type="hidden" asp-for="FieldId" />
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="mb-3">
        <label asp-for="FieldName" class="form-label"></label>
        <input disabled asp-for="FieldName" type="text" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="TypeName" class="form-label"></label>
        <select disabled asp-for="TypeId" class="form-select" asp-items="ViewBag.TypeId">
            <option  value="">--Select Type--</option>

        </select>
    </div>
    <div class="mb-3">
        <label asp-for="Placeholder" class="form-label"></label>
        <input disabled asp-for="Placeholder" type="text" class="form-control">
    </div>

            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">
                   Delete
                </button>
            <a asp-action="Index" class="btn btn-secondary">Back</a>
            <form method="post" asp-action="Delete">

                <input type="hidden" asp-for="FieldId" />
                <div class="modal" id="deleteModal">
                    <div class="modal-dialog">
                        <div class="modal-content">

                            <!-- Modal Header -->
                            <div class="modal-header">
                                <h4 class="modal-title">Delete Confirmed</h4>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                            </div>

                            <!-- Modal body -->
                            <div class="modal-body">
                                Are you sure you want to delete this field
                            </div>

                            <!-- Modal footer -->
                            <div class="modal-footer">
                                <input type="submit" class="btn btn-danger" name="name" value="Delete" />
                               
                            </div>

                        </div>
                    </div>
                </div>
     
    </form>
</div>
</div>
</div>

@* <script>
    function confirmDelete(id) {
        if (confirm("Are you sure you want to delete this field?")) {
            fetch('/Field/DeleteConfirmed?id=' + id, {
                method: 'POST'
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    alert("Deleted  successfully!");
                    location.reload(); 
                } else {
                    alert("Error: " + data.message);
                }
            })
            .catch(error => console.error('Error:', error));
        }
    }
</script> *@

StreamLinerApp/Areas/scp/Views/Field/Edit.cshtml
 @model StreamLinerViewModelLayer.ModelDTO.FieldDTO 


@{
    ViewData["Title"] = "Fields";
}
<br />
<div class="container">
    <h3> @ViewData["controller"] -   @ViewData["action"]   </h3>
</div>
<hr />


<div class="container mt-5">

    <div class="row">

        <div class="col-md-6">


            <form method="post"  asp-action="Edit" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="mb-3">
                    <label asp-for="FieldName" class="form-label"></label>
                    <input asp-for="FieldName" type="text" class="form-control" >
                </div>
                <div class="mb-3">
                    <label asp-for="TypeName" class="form-label"></label>
                    <select asp-for="TypeId" class="form-select" asp-items="ViewBag.TypeId">
                        <option value="">--Select Type--</option>
                    
                    </select>
                </div>
                <div class="mb-3">
                    <label asp-for="Placeholder" class="form-label"></label>
                    <input asp-for="Placeholder" type="text" class="form-control">
                </div>
              

                <button type="submit" class="btn btn-primary">Save</button>
                <a asp-action="Index" class="btn btn-secondary">Back</a>
            </form>
        </div>
    </div>
</div>

StreamLinerApp/Areas/scp/Views/Field/Index.cshtml
@model IEnumerable<StreamLinerViewModelLayer.ModelDTO.FieldDTO>

@{
    ViewData["Title"] = "Fields";
}
 <br />
<div class="row container">
    <div class="col-4">
        <h3>   @ViewData["controller"]  @ViewData["action"] </h3>
    </div>
    <div class="col-8 text-right">
        <a asp-action="Create" class="btn btn-primary"><i class="fa fa-plus"></i> New Field</a>
    </div>
</div>
<hr />

<div class="row ">

    <div class="col-12 p-4">
        <table class="table table-hover">
            <thead>
                <tr>
                @*     <th><input type="checkbox" name="" id=""></th> *@
                    <th>Field Name</th>
                    <th>Type</th>
                    <th>Is Required</th>
                    <th>Placeholder</th>
                    <th style="width:150px;"> Action </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                       @*  <td><input type="checkbox" name="" id=""></td> *@
                        <td>@item.FieldName</td>
                        <td>@item.TypeName</td>
                        <td>@item.IsRequired</td>
                        <td>@item.Placeholder</td>
                        <td>

                            <a asp-controller="Field" asp-action="Edit" asp-route-id="@item.FieldId" class="btn btn-primary"> <i class="fa fa-edit"></i></a>
                            <a asp-controller="Field" asp-action="Delete" asp-route-id="@item.FieldId" class="btn btn-danger"><i class="fa fa-trash"></i> </a>

                        </td>

                    </tr>
                }


            </tbody>
        </table>

    </div>

</div>